name = "CommonEq"
uuid = "3709ef60-1bee-4518-9f2f-acd86f176c50"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "0.2.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
